### ISSUE TITLE
unable to decompress a .ftl using the instructions but found a workaround

### ISSUE THREAD

**Issue by Gussak** [meszaros-lajos-gyorgy/arx-level-json-converter#1]
hi!   
I tried the `arx-header-size` and `explode` but they failed.  
So I managed to unpack using this:  https://github.com/Gussak/ArxLaetansMod/blob/main/plugins/blender/arx_addon/unpackFtl.simpleCmdLine.sh that calls a minimal .py script that uses the arxIO lib to unpack the .ftl file

PS.: the conversion to json works great, I further patch it using `sed` to finally prepare the .ftl models, thx!

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! FTL files are not compressed with pkware, you don't need to use explode, just call arx-convert. The documentation's example section does not take that into account, it expects the input to be compressed. I'll update it in a second...

**Comment by meszaros-lajos-gyorgy** [comment]
Added two general purpose scripts in the readme for unpacking and repacking any files.
